name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 

      - name: Criando arquivo .env
        working-directory: ./library_back
        run: |
          echo POSTGRES_DB=library_db >> .env
          echo POSTGRES_USER=postgres >> .env
          echo POSTGRES_PASSWORD=password >> .env
          echo POSTGRES_HOST=database >> .env
          echo POSTGRES_PORT=5432 >> .env
          cat .env
      - name: Build backend e frontend
        working-directory: ./
        run: docker-compose up -d

  tests:
    runs-on:  ubuntu-latest
    needs: UP_Test
    steps:
      - uses: actions/checkout@v3
      - name: Run Docker-compose
        run: docker-compose up -d
      - name: Run backend makemigration
        run: docker-compose exec -T backend python manage.py makemigrations
      - name: Run backend migrate fake 
        run: docker-compose exec -T backend python manage.py migrate --fake
      - name: Run backend test 
        run: docker-compose exec -T backend python manage.py test
      - name: Run frontend tests
        run: docker-compose exec -T frontend npm test -- --watchAll=false